// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badge: string;
  icon: string;
  noticeButton: string;
  popover: string;
  tabs: string;
}
export const cssExports: CssExports;
export default cssExports;
