// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatar: string;
  bottomBar: string;
  datetime: string;
  description: string;
  extra: string;
  iconElement: string;
  item: string;
  list: string;
  loadMore: string;
  loadedAll: string;
  meta: string;
  notFound: string;
  read: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
