// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  container: string;
  content: string;
  desc: string;
  header: string;
  icon: string;
  lang: string;
  logo: string;
  main: string;
  other: string;
  prefixIcon: string;
  register: string;
  title: string;
  top: string;
};
export const cssExports: CssExports;
export default cssExports;
